#! /usr/bin/env bash

# check correct invocation
if [[ "$#" -gt 1 ]]; then
	echo "Usage: backup-database"
	exit 1
fi

# check config parameters common to all scripts
$(dirname $0)/private/check-config
check_config_status=$?
if [ $check_config_status -ne 0 ]; then
    exit $check_config_status
fi

# include config
source $(dirname $0)/.env

# check required database parameters
if [[ -z "$DB_DRIVER" || -z "$DB_DATABASE"  || -z "$DB_USER" ]]; then
	echo "Incomplete database configuration, exiting."
	echo "The following configuration parameters are required: DB_DRIVER, DB_DATABASE, DB_USER, DB_PASSWORD"
	exit 2
fi

# check required storage parameters
if [[ -z "$STORAGE_TYPE" || -z "$STORAGE_ROOT" ]]; then
	echo "Missing storage configuration parameters, exiting."
	echo "The following parameters are required: STORAGE_TYPE, STORAGE_ROOT"
	exit 3
fi

site_name="$(basename "$PATH_TO_SITE")"

echo "Backing up database of craft site $site_name."

echo "Creating database dump..."
timestamp="$(date +%Y%m%d_%H%I%SMEZ)"
temp_dir="$(mktemp -d)"
db_dump="${site_name}_$timestamp.sql"

$(dirname $0)/private/database-dump > "$temp_dir/$db_dump"

echo "Creating archive to be copied to storage..."
archive="${db_dump}.gz"
gzip -c "$temp_dir/$db_dump" > "${temp_dir}/${archive}"

echo "Copying archive..."
$(dirname $0)/private/storage-copy "$temp_dir/$archive" "$STORAGE_ROOT/$site_name/$archive"

echo "Cleaning up"
rm -rf "$temp_dir"
