#! /usr/bin/env bash

# check correct invocation
if [[ "$#" -gt 0 ]]; then
	echo "Usage: backup-assets"
	exit 1
fi

# check config parameters common to all scripts
$(dirname $0)/private/check-config
check_config_status=$?
if [ $check_config_status -ne 0 ]; then
    exit $check_config_status
fi

# include config
source $(dirname $0)/.env

# check required file system parameters
if [[ -z "$ASSET_DIRS" ]]; then
	echo "Missing file system configuration parameter ASSET_DIRS, exiting."
	exit 2
fi

# check required storage parameters
if [[ -z "$STORAGE_TYPE" || -z "$STORAGE_ROOT" ]]; then
	echo "Missing storage configuration parameters, exiting."
	echo "The following parameters are required: STORAGE_TYPE, STORAGE_ROOT"
	exit 3
fi

echo "Backing up assets of project $PROJECT_NAME."
timestamp="$(date +%Y%m%dT%H%I%S)"
temp_dir="$(mktemp -d)"

echo "Creating archive of assets..."
archive="${PROJECT_NAME}_${timestamp}.tar.gz"
tar -cz -f "$temp_dir/$archive" -C "$PROJECT_ROOT" --files-from <(printf "%s\n" "${ASSET_DIRS[@]}")

echo "Copying archive..."
$(dirname $0)/private/storage-copy "$temp_dir/$archive" "$STORAGE_ROOT/$archive"

echo "Cleaning up"
rm -rf "$temp_dir"
