#! /usr/bin/env bash

# check correct invocation
if [[ "$#" -gt 0 ]]; then
    echo "usage: ls-database-backups"
    exit 1
fi

# check config parameters common to all scripts
$(dirname $0)/private/check-config
check_config_status=$?
if [ $check_config_status -ne 0 ]; then
    exit $check_config_status
fi

# include config
source $(dirname $0)/.env

# check required database parameters
if [[ -z "$DB_DRIVER" || -z "$DB_DATABASE"  || -z "$DB_USER" ]]; then
    echo "Incomplete database configuration, exiting."
    echo "The following configuration parameters are required: DB_DRIVER, DB_DATABASE, DB_USER, DB_PASSWORD"
    exit 2
fi

# check required storage parameters
if [[ -z "$STORAGE_TYPE" || -z "$STORAGE_ROOT" ]]; then
    echo "Missing storage configuration parameters, exiting."
    echo "The following parameters are required: STORAGE_TYPE, STORAGE_ROOT"
    exit 3
fi

echo "Listing database backups of project $PROJECT_NAME."

list_pattern="${STORAGE_ROOT}/*.sql.gz"

list_cmd=$(dirname $0)/private/storage-list
"$list_cmd" "$list_pattern"
