#! /usr/bin/env bash

# check correct invocation
if [[ "$#" -gt 1 ]]; then
    echo "usage: restore-database [archive-filename]"
    exit 1
fi

# check config parameters common to all scripts
$(dirname $0)/private/check-config
check_config_status=$?
if [ $check_config_status -ne 0 ]; then
    exit $check_config_status
fi

# include .env file if it exists
config_path=$(dirname $0)/.env
if [[ -f "$config_path" ]]; then
    source "$config_path"
fi

# check required database parameters
if [[ -z "$DB_DRIVER" || -z "$DB_DATABASE"  || -z "$DB_USER" ]]; then
    echo "Incomplete database configuration, exiting."
    echo "The following configuration parameters are required: DB_DRIVER, DB_DATABASE, DB_USER, DB_PASSWORD"
    exit 2
fi

# check required storage parameters
if [[ -z "$STORAGE_TYPE" || -z "$STORAGE_ROOT" ]]; then
    echo "Missing storage configuration parameters, exiting."
    echo "The following parameters are required: STORAGE_TYPE, STORAGE_ROOT"
    exit 3
fi

echo "Restoring database of project $PROJECT_NAME."

if  [[ -z "$1" ]]; then
    echo "Looking for most current backup..."
    list_pattern="${STORAGE_ROOT}/*.sql.gz"
else
    echo "Looking for backup $1"
    list_pattern="$1"
fi

list_cmd=$(dirname $0)/private/storage-list
archive_url=$("$list_cmd" "$list_pattern" | tail -1)

if [[ -z "$archive_url" ]]; then
    echo "Database backup(s) not found, exiting."
    exit 4
fi

echo "Found $archive_url"

temp_dir="$(mktemp -d)"

echo "Copying database dump..."
$(dirname $0)/private/storage-copy "$archive_url" "$temp_dir"

echo "Unzipping..."
gunzip "$temp_dir"/*.sql.gz

echo "Restoring database..."
$(dirname $0)/private/database-restore < "$temp_dir"/*.sql
