#! /usr/bin/env bash

# check correct invocation
if [[ "$#" -gt 0 ]]; then
    echo "usage: set-perms"
    exit 1
fi

# check config parameters common to all scripts
$(dirname $0)/private/check-config
check_config_status=$?
if [ $check_config_status -ne 0 ]; then
    exit $check_config_status
fi

# include config
source $(dirname $0)/.env

# check required file system parameters
if [[ -z "$FS_USER"  || -z "$FS_GROUP" ]]; then
    echo "Missing file system configuration parameters, exiting."
    echo "The following parameters are required: FS_USER, FS_GROUP"
    exit 2
fi

craft_writable_dirs=(
    "web/cpresources"
    "storage"
)

if [[ -z "$ASSET_DIRS" ]]; then
    writeable_dirs=("${craft_writable_dirs[@]}")
else
    writeable_dirs=("${craft_writable_dirs[@]}" "${ASSET_DIRS[@]}")
fi

writeable_dir_perms=775
writeable_file_perms=664

for dir in ${writeable_dirs[@]}
do
    fullpath=${PROJECT_ROOT}/${dir}
    if [[ -d "${fullpath}" ]] ; then
        echo "Fixing permissions for ${fullpath}"
        chown -R "$FS_USER":"$FS_GROUP" "${fullpath}"
        chmod -R $writeable_dir_perms "${fullpath}"
        find "${fullpath}" -type f ! -name "*.sh" -exec chmod $writeable_file_perms {} \;
    else
        echo "Creating directory ${fullpath}"
        mkdir "${fullpath}"
        chmod -R $writeable_dir_perms "${fullpath}"
    fi
done
