#! /usr/bin/env bash

# include .env file if it exists
config_path=$(dirname $0)/../.env
if [[ -f "$config_path" ]]; then
    source "$config_path"
fi

# check project name
if [[ -z "$PROJECT_NAME" ]]; then
    echo "Missing configuration parameter PROJECT_NAME, exiting."
    exit 12
fi

# check path to site config param
if [[ -z "$PROJECT_ROOT" ]]; then
    echo "Missing configuration parameter PROJECT_ROOT, exiting."
    exit 12
fi

# check that project specified by PROJECT_ROOT exists
if [[ ! -d "$PROJECT_ROOT" ]]; then
    echo "Craft project at $PROJECT_ROOT not found, exiting."
    exit 13
fi
