#! /usr/bin/env bash

# check that config file exists
config_path=$(dirname $0)/../.env
if [[ ! -f "$config_path" ]]; then
	echo "Could not find configuration file .env, exiting."
	exit 11
fi

# include config file
source $(dirname $0)/../.env

# check path to site config param
if [[ -z "$PATH_TO_SITE" ]]; then
	echo "Missing configuration parameter PATH_TO_SITE, exiting."
	exit 12
fi

# check that project specified by PATH_TO_SITE exists
if [[ ! -d "$PATH_TO_SITE" ]]; then
	echo "Craft project at $PATH_TO_SITE not found, exiting."
	exit 13
fi
