#! /usr/bin/env bash

# check that config file exists
config_path=$(dirname $0)/../.env
if [[ ! -f "$config_path" ]]; then
    echo "Could not find configuration file .env, exiting."
    exit 11
fi

# include config file
source $(dirname $0)/../.env

# check project name
if [[ -z "$PROJECT_NAME" ]]; then
    echo "Missing configuration parameter PROJECT_NAME, exiting."
    exit 12
fi

# check path to site config param
if [[ -z "$PROJECT_ROOT" ]]; then
    echo "Missing configuration parameter PROJECT_ROOT, exiting."
    exit 12
fi

# check that project specified by PROJECT_ROOT exists
if [[ ! -d "$PROJECT_ROOT" ]]; then
    echo "Craft project at $PROJECT_ROOT not found, exiting."
    exit 13
fi
