#! /usr/bin/env bash

#read coniguration
source $(dirname $0)/../.env

pwd_arg=""

if [[ ! -z "$DB_PASSWORD" ]]; then
    pwd_arg='--password='"$DB_PASSWORD"
fi

# dump database to stdout
mysqldump -h"${DB_SERVER:-localhost}" --port=${DB_PORT:-3306} -u"$DB_USER" $pwd_arg --databases "$DB_DATABASE"

