#! /usr/bin/env bash

# include .env file if it exists
config_path=$(dirname $0)/../.env
if [[ -f "$config_path" ]]; then
    source "$config_path"
fi

pwd_arg=""

if [[ ! -z "$DB_PASSWORD" ]]; then
    pwd_arg='--password='"$DB_PASSWORD"
fi

# dump database to stdout
mysqldump -h"${DB_SERVER:-localhost}" --port=${DB_PORT:-3306} -u"$DB_USER" $pwd_arg --databases "$DB_DATABASE"

