#! /usr/bin/env bash

# include .env file if it exists
config_path=$(dirname $0)/../.env
if [[ -f "$config_path" ]]; then
    source "$config_path"
fi

db_restore_cmd=$(dirname $0)/database-restore-"$DB_DRIVER"
$db_restore_cmd
