#! /usr/bin/env bash

#read coniguration
source $(dirname $0)/../.env

pwd_arg=""

if [[ ! -z "$DB_PASSWORD" ]]; then
    pwd_arg='--password='"$DB_PASSWORD"
fi

# restore the database from stdin
mysql -h"${DB_SERVER:-localhost}" --port=${DB_PORT:-3306} -u"$DB_USER" $pwd_arg "$DB_DATABASE"
