#! /usr/bin/env bash

# include .env file if it exists
config_path=$(dirname $0)/../.env
if [[ -f "$config_path" ]]; then
    source "$config_path"
fi

copy_cmd=$(dirname $0)/storage-copy-"$STORAGE_TYPE"

$copy_cmd $1 $2
